unms: fix logrotate
The unms logrotate file has the wrong mode, and thus not effective,
Checked manually, previously would get:

```
error: Ignoring /etc/logrotate.d/unms because of bad file mode - must be 0644 or 0444.
```

Change-type: patch
Signed-off-by: Gergely Imreh <gergely@balena.io>